language: android
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30

before_install:
  - chmod +x gradlew
  - echo yes | sdkmanager "platforms;android-30"

script:
  - ./gradlew :mobile:jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
