language: android
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29

before_install:
  - chmod +x gradlew
  - echo yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew :mobile:jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
